apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels: 
    name: mysql
  namespace: aulainfra
spec:
  containers:
    - image: mysql
      name: mysql
      env:
          # Usar senha 
        - name: MYSQL_ROOT_PASSWORD
          value: root
      ports:
        - containerPort: 3306
          name: mysql